<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Exercise 03 - Practice Options Data (without answers)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 60px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 65px;
  margin-top: -65px;
}

.section h2 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h3 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h4 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h5 {
  padding-top: 65px;
  margin-top: -65px;
}
.section h6 {
  padding-top: 65px;
  margin-top: -65px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">FM 5990</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="instructor.html">Instructor</a>
</li>
<li>
  <a href="weekly_plan.html">Weekly Plan</a>
</li>
<li>
  <a href="tutorials.html">Tutorials</a>
</li>
<li>
  <a href="slides.html">Slides</a>
</li>
<li>
  <a href="self_study.html">Self-Study</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="q_and_a.html">Q &amp; A</a>
</li>
<li>
  <a href="partners.html">Partners</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Exercise 03 - Practice Options Data (without answers)</h1>

</div>


<p>This exercise set is going to be structured a little been differently. In the first place, all the questions are in this R Markdown file, because I want you to get comfortable with this file format. Additionally, many of the questions will start with a completed query that you will be asked to modify. Much can be learned from reading completed code and understanding it enough to modify it.</p>
<p>This document is not intended to be <code>knit</code>. Instead, read through it in the RStudio source window, and execute the code in chunks (ctrl/cmd + shift + enter) or by highlighting lines (ctrl/cmd + enter). I have been using in-line output as I create this document and I’m enjoying. I encourage you to expriment with both in-line and console output and see what you like best.</p>
<p>   </p>
<div id="preliminaries" class="section level4">
<h4>Preliminaries</h4>
<ol style="list-style-type: decimal">
<li>Check the working directory of this file and then try to change the working directory to your desktop. To run all a single line of code in a chunk press <code>ctrl/cmd + enter</code>, and the line of code that your cursor is on will be executed. To run an entire chunk, press <code>ctrl/cmd + shift + enter</code>. You don’t have to knit the document to run code.</li>
</ol>
<pre class="r"><code># You should get an error when you try to change the working directory.  Basically, R Markdown notebooks are setup to keep the working directory the same as the folder that contains that the .Rmd file itself.</code></pre>
<p> </p>
<ol start="2" style="list-style-type: decimal">
<li>Load <code>readr</code> and <code>dplyr</code> into this R session.</li>
</ol>
<pre class="r"><code>library(readr)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p> </p>
<ol start="3" style="list-style-type: decimal">
<li>Put the two CSVs <code>data_practice_market_history</code> and <code>data_practice_option_history</code> into the same folder as this .Rmd file and then read in the CSVs (using <code>readr::read_csv()</code>) into two data frames called <code>df_market_history</code> and <code>df_option_history</code>.</li>
</ol>
<pre class="r"><code># When you use `read_csv()` put the following code as the second arugument `col_types = cols()` in order to avoid annoying warning messages.
df_market_history &lt;- read_csv(&quot;data_practice_market_history.csv&quot;, col_types = cols())
df_option_history &lt;- read_csv(&quot;data_practice_option_history.csv&quot;, col_types = cols())</code></pre>
<p>   </p>
</div>
<div id="exploring-df_market_history" class="section level4">
<h4>Exploring <code>df_market_history</code></h4>
<ol start="4" style="list-style-type: decimal">
<li>Let’s look at all the underlyings that are represented in <code>df_market_history</code> on 8/16/2018. How many are there? Modify the query to see how many underlyings there are on 12/16/2013?</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% 
  filter(trade_date == as.Date(&quot;2013-08-16&quot;)) %&gt;% 
  distinct(underlying)</code></pre>
<pre><code>## # A tibble: 100 x 1
##    underlying
##    &lt;chr&gt;     
##  1 SPY       
##  2 IWM       
##  3 XLF       
##  4 EEM       
##  5 QQQ       
##  6 FXI       
##  7 EFA       
##  8 GLD       
##  9 EWZ       
## 10 IYR       
## # ... with 90 more rows</code></pre>
<p> </p>
<ol start="5" style="list-style-type: decimal">
<li>The following query counts the number of underlyings that are accounted for on each trade date in <code>df_market_history</code>. About how many underlyings are there each day?</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% 
  group_by(trade_date) %&gt;% 
  summarize(num_und = n_distinct(underlying)) %&gt;% 
  arrange(trade_date)</code></pre>
<pre><code>## # A tibble: 106 x 2
##    trade_date num_und
##    &lt;date&gt;       &lt;int&gt;
##  1 2013-08-16     100
##  2 2013-08-19     100
##  3 2013-08-20      98
##  4 2013-08-21     100
##  5 2013-08-22     100
##  6 2013-08-23     100
##  7 2013-08-26     100
##  8 2013-08-27     100
##  9 2013-08-28     100
## 10 2013-08-29      99
## # ... with 96 more rows</code></pre>
<p> </p>
<ol start="6" style="list-style-type: decimal">
<li>The following query returns a list of all the trade dates that are represented in <code>df_market_history</code>. Add a use of <code>top_n()</code> with <code>%&gt;%</code> in order to isolate the earliest date and the latest date.</li>
</ol>
<pre class="r"><code># earliest is 8/16/2013
# latest is 1/16/2014
df_market_history %&gt;% distinct(trade_date) </code></pre>
<pre><code>## # A tibble: 106 x 1
##    trade_date
##    &lt;date&gt;    
##  1 2013-08-16
##  2 2013-08-19
##  3 2013-08-20
##  4 2013-08-21
##  5 2013-08-22
##  6 2013-08-23
##  7 2013-08-26
##  8 2013-08-27
##  9 2013-08-28
## 10 2013-08-29
## # ... with 96 more rows</code></pre>
<p> </p>
<ol start="7" style="list-style-type: decimal">
<li>The follow query returns a tibble consisting of all the distinct expirations represented in the data for a trade date of 8/16/2013 - there should be only one, 9/21/2013. Modify the query to see how many SPY expirations are in the data set for a trade date of 9/20/2013. Is it the same expiration that you found for 8/16? See what happens when you remove the <code>underlying == &quot;SPY&quot;</code> filter - what conclusion can you make?</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% 
  filter(underlying == &quot;SPY&quot;) %&gt;% 
  filter(trade_date == as.Date(&quot;2013-08-16&quot;)) %&gt;% 
  distinct(expiration)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   expiration
##   &lt;date&gt;    
## 1 2013-09-21</code></pre>
<p> </p>
<ol start="8" style="list-style-type: decimal">
<li>The follow query counts the number of distinct <code>expiration</code> that can be found for each <code>trade_date</code>. What I want you to see is that for each <code>trade_date</code>, there is only one <code>expiration</code> in the data set. There 106 trade dates, so we could really just look at the entire dataframe by piping into <code>View()</code> to verify that <code>num_exps = 1</code> for all trade dates. However, if there were thousands of trade dates this would be less feasible.</li>
</ol>
<p>Modify this code so that you can check the <code>min()</code> and <code>max()</code> of <code>num_exps</code>. An extra 100 nerd points if you can do it without creating an intermediate dataframe - i.e. if you can do it with just pipes.</p>
<pre class="r"><code># The main point of the exercise is just to see that for each trade date there is only data for one expiration.
df_market_history %&gt;% 
  group_by(trade_date) %&gt;% 
  summarize(num_exps = n_distinct(expiration)) %&gt;% 
  arrange(trade_date)</code></pre>
<pre><code>## # A tibble: 106 x 2
##    trade_date num_exps
##    &lt;date&gt;        &lt;int&gt;
##  1 2013-08-16        1
##  2 2013-08-19        1
##  3 2013-08-20        1
##  4 2013-08-21        1
##  5 2013-08-22        1
##  6 2013-08-23        1
##  7 2013-08-26        1
##  8 2013-08-27        1
##  9 2013-08-28        1
## 10 2013-08-29        1
## # ... with 96 more rows</code></pre>
<p> </p>
<ol start="9" style="list-style-type: decimal">
<li>The following query shows which <code>expiration</code> is given on each <code>trade_date</code>. Why is it OK that I use <code>min()</code> in the summarize function? Try using <code>max()</code> instead and see that you get the same answer. Pipe this query into <code>View()</code> and look at how <code>exp_date</code> changes as you move through time.</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% 
  group_by(trade_date) %&gt;% 
  summarize(exp_date = min(expiration)) %&gt;% 
  arrange(trade_date)</code></pre>
<pre><code>## # A tibble: 106 x 2
##    trade_date exp_date  
##    &lt;date&gt;     &lt;date&gt;    
##  1 2013-08-16 2013-09-21
##  2 2013-08-19 2013-09-21
##  3 2013-08-20 2013-09-21
##  4 2013-08-21 2013-09-21
##  5 2013-08-22 2013-09-21
##  6 2013-08-23 2013-09-21
##  7 2013-08-26 2013-09-21
##  8 2013-08-27 2013-09-21
##  9 2013-08-28 2013-09-21
## 10 2013-08-29 2013-09-21
## # ... with 96 more rows</code></pre>
<p> </p>
<ol start="10" style="list-style-type: decimal">
<li>The following query checks for OTM (out-of-the-money) calls in <code>df_market_history</code> - notice that we use <code>implied_forward</code> to determine moniness of options. Modify the query to check for ITM (in-the-money) calls. Did you find any? Create another query to check for OTM/ITM puts. Do you find any ITM puts?</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% filter(type == &quot;call&quot;) %&gt;% 
                      filter(strike &gt; implied_forward)</code></pre>
<pre><code>## # A tibble: 55,855 x 18
##    trade_date option_symbol underlying type  expiration   d2x strike   upx
##    &lt;date&gt;     &lt;chr&gt;         &lt;chr&gt;      &lt;chr&gt; &lt;date&gt;     &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    166  166.
##  2 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    167  166.
##  3 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    168  166.
##  4 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    169  166.
##  5 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    170  166.
##  6 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    171  166.
##  7 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    172  166.
##  8 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    173  166.
##  9 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    174  166.
## 10 2013-08-16 SPY130921C00… SPY        call  2013-09-21    24    175  166.
## # ... with 55,845 more rows, and 10 more variables: bid &lt;dbl&gt;, ask &lt;dbl&gt;,
## #   mid &lt;dbl&gt;, volume &lt;int&gt;, open_interest &lt;int&gt;, implied_forward &lt;dbl&gt;,
## #   implied_vol &lt;dbl&gt;, delta &lt;dbl&gt;, atm_volatility &lt;dbl&gt;, swap_rate &lt;dbl&gt;</code></pre>
<p> </p>
<p><strong>Summary</strong></p>
<p>Here are some facts about the <code>df_market_history</code> dataset. We have demonstrated a lot of these by the previous exercises. Note that the numbers below do not correspond to the exercises above.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Context:</strong> For nearly all underlyings, there is one expiration date per month - the third Saturday. For most underlyings, 3 or 4 expirations are actively traded at any given time. The nearest expiration is sometimes referred to as the <em>front-month</em>.</p></li>
<li><p>In <code>df_market_history</code>, for each trade date, only front-month options are included.</p></li>
<li><p>Notice that on Friday 8/16/2013, all the options have an expiration date of 9/21/2013. This remains true until Friday 9/20/2013, which is the final trading day of the 9/21 expiration. On that day, the all options have an expiration of 10/19/2013, which remains the case until Friday 10/18.</p></li>
<li><p>This data set contains option data from the 100 most liquid ETF underlyings.</p></li>
<li><p>Only OTM options are represented in the data.</p></li>
<li><p><strong>Putting It Together:</strong> <code>df_market_history</code> consists of EOD option prices from 8/16/2013 to 1/16/2014, for about 100 liquid ETF underlyings. On any given day, only fronth-month, OTM option prices are included.</p></li>
<li><p><strong>Looking Ahead:</strong> for the option trading strategies we are going to consider, we will only be trading front-month, OTM options.</p></li>
</ol>
<p>   </p>
</div>
<div id="exploring-df_option_history" class="section level4">
<h4>Exploring <code>df_option_history</code></h4>
<ol start="11" style="list-style-type: decimal">
<li>We can use the following query see all the dates for which the September 2013 SPY 166 put was an OTM option. Recall that <code>df_market_history</code> starts at 8/16/2013, so we can conclude that this options was ITM from 8/16 to 8/22. Also, notice the gap between 8/23 and 9/9, which means that the option was again ITM from 8/24 to 9/8.</li>
</ol>
<pre class="r"><code>df_market_history %&gt;% 
  filter(underlying == &quot;SPY&quot;) %&gt;% 
  filter(expiration == as.Date(&quot;2013-09-21&quot;)) %&gt;% 
  filter(type == &quot;put&quot;) %&gt;% 
  filter(strike == 166) %&gt;% 
  arrange(trade_date)</code></pre>
<pre><code>## # A tibble: 8 x 18
##   trade_date option_symbol underlying type  expiration   d2x strike   upx
##   &lt;date&gt;     &lt;chr&gt;         &lt;chr&gt;      &lt;chr&gt; &lt;date&gt;     &lt;int&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 2013-08-23 SPY130921P00… SPY        put   2013-09-21    19    166  167.
## 2 2013-09-09 SPY130921P00… SPY        put   2013-09-21     9    166  168.
## 3 2013-09-10 SPY130921P00… SPY        put   2013-09-21     8    166  169.
## 4 2013-09-11 SPY130921P00… SPY        put   2013-09-21     7    166  169.
## 5 2013-09-12 SPY130921P00… SPY        put   2013-09-21     6    166  169.
## 6 2013-09-13 SPY130921P00… SPY        put   2013-09-21     5    166  169.
## 7 2013-09-16 SPY130921P00… SPY        put   2013-09-21     4    166  170.
## 8 2013-09-17 SPY130921P00… SPY        put   2013-09-21     3    166  171.
## # ... with 10 more variables: bid &lt;dbl&gt;, ask &lt;dbl&gt;, mid &lt;dbl&gt;,
## #   volume &lt;int&gt;, open_interest &lt;int&gt;, implied_forward &lt;dbl&gt;,
## #   implied_vol &lt;dbl&gt;, delta &lt;dbl&gt;, atm_volatility &lt;dbl&gt;, swap_rate &lt;dbl&gt;</code></pre>
<ol start="12" style="list-style-type: decimal">
<li>This query shows all the entries related to the September 2013 SPY 166 put in <code>df_option_history</code>. Notice that after 8/23, all trade dates are represented. (Bonus Challenge: use the <code>bizdays</code> package to verify that this is the case - this will probably be time consuming to figure out so don’t worry about it too much unless you’re feeling like a gangster.)</li>
</ol>
<pre class="r"><code>df_option_history %&gt;% 
  filter(underlying == &quot;SPY&quot;) %&gt;% 
  filter(expiration == as.Date(&quot;2013-09-21&quot;)) %&gt;% 
  filter(type == &quot;put&quot;) %&gt;% 
  filter(strike == 166) %&gt;% 
  arrange(trade_date)</code></pre>
<pre><code>## # A tibble: 20 x 13
##    trade_date option_symbol underlying type  expiration strike   upx   bid
##    &lt;date&gt;     &lt;chr&gt;         &lt;chr&gt;      &lt;chr&gt; &lt;date&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 2013-08-23 SPY130921P00… SPY        put   2013-09-21    166  167.  2.32
##  2 2013-08-26 SPY130921P00… SPY        put   2013-09-21    166  166   2.68
##  3 2013-08-27 SPY130921P00… SPY        put   2013-09-21    166  163.  4.28
##  4 2013-08-28 SPY130921P00… SPY        put   2013-09-21    166  164.  3.92
##  5 2013-08-29 SPY130921P00… SPY        put   2013-09-21    166  164.  3.74
##  6 2013-08-30 SPY130921P00… SPY        put   2013-09-21    166  164.  3.88
##  7 2013-09-03 SPY130921P00… SPY        put   2013-09-21    166  164.  3.39
##  8 2013-09-04 SPY130921P00… SPY        put   2013-09-21    166  166.  2.4 
##  9 2013-09-05 SPY130921P00… SPY        put   2013-09-21    166  166.  2.33
## 10 2013-09-06 SPY130921P00… SPY        put   2013-09-21    166  166.  2.24
## 11 2013-09-09 SPY130921P00… SPY        put   2013-09-21    166  168.  1.31
## 12 2013-09-10 SPY130921P00… SPY        put   2013-09-21    166  169.  0.73
## 13 2013-09-11 SPY130921P00… SPY        put   2013-09-21    166  169.  0.48
## 14 2013-09-12 SPY130921P00… SPY        put   2013-09-21    166  169.  0.53
## 15 2013-09-13 SPY130921P00… SPY        put   2013-09-21    166  169.  0.38
## 16 2013-09-16 SPY130921P00… SPY        put   2013-09-21    166  170.  0.21
## 17 2013-09-17 SPY130921P00… SPY        put   2013-09-21    166  171.  0.15
## 18 2013-09-18 SPY130921P00… SPY        put   2013-09-21    166  173.  0.03
## 19 2013-09-19 SPY130921P00… SPY        put   2013-09-21    166  173.  0.02
## 20 2013-09-20 SPY130921P00… SPY        put   2013-09-21    166  171.  0   
## # ... with 5 more variables: ask &lt;dbl&gt;, implied_vol &lt;dbl&gt;, delta &lt;dbl&gt;,
## #   volume &lt;int&gt;, open_interest &lt;int&gt;</code></pre>
<p><strong>Summary</strong></p>
<p>Here are some facts about <code>df_option_history</code>.</p>
<ol style="list-style-type: decimal">
<li><p>Once an option shows up in <code>df_market_history</code> it will show up in <code>df_option_history</code> starting on that trade date, and <em>for all subsequent trade dates until expiration</em>.</p></li>
<li><p>When we do backtesting, if our trading strategy requires trading on a given <code>trade_date</code>, we will trade only OTM options, hece the options we will trade must be in <code>df_market_history</code> on that date.</p></li>
<li><p>We will then use <code>df_option_history</code> to calculate the daily pnl for that trade, for all <code>trade_dates</code> on which we hold the posiiton.</p></li>
</ol>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
