---
title: "FM 5990"
---

This is the website for FM 5990 - Fall 2018.

We meet Tuesdays 5:30p-7:10p at Vincent 364.

&nbsp;

#### Announcements


##### 12/3/2018

- Added a section on Python in the Self-Study page.  I'm sure you were going to be bored over winter break, so now you will have plenty to do.

##### 11/27/2018

- **REMINDER:** projects are due this Friday 11/30, by 12p noon.  Today's class is going to be dedicated to answering any questions that you have about the project.

- Slides 10 on package exploration have been uploaded.

##### 11/12/2018

- **NOTE:** TA's office hours this week have been changed to Friday 11/16 from 12p-2p.

##### 11/11/2018
- Instructions have been added to the *Project* page.  You can download the starter Rstudio project from the Google Drive folder.

##### 11/6/2018

- Updated the *Tutorials & Exercises* section so now you can download everything at once in a single R Studio project.

- Added Slides 8 and 9.

- Added *Project* page.  All the materials you will need for the project will be up here later this week.


##### 10/9/2018
- NO CLASS next week 10/16.  Rather, I am going to meet with the groups individually to discuss the project and to see where folks are in their understanding of the material. See the weekly plan for further instructions.

- Tutorial 8 on Data Visualization has been uploaded.  

##### 10/4/2018
- **New Office Hours:** Immediately after class, or by appointment.

##### 10/2/2018
- I posted Tutorial 07 that we will go over in class.  Please download it and put the **Options History** data sets into the same directory so we can read them in.

- No new reading assignments for next week, this will give folks an opportunity to catch-up.


##### 9/28/2018
- Posted a set of exercises for *Option History Practice*.  It's an R Markdown notebook, so enjoy.

##### 9/25/2018

- Posted a new data set called *Option History Practice* - there will be exercises posted for this data in the next day or two.

- Posted a new tutorial which is an introduction to R Markdown.

##### 9/22/2018

- Posted exercises for the *OCC Volume* data.

- Students are welcome to create scripts for the exercises and turn them in for feedback from the TA.  I will go over instructions for doing so during class on 9/25.

##### 9/21/2018

- Assignment for 9/25/2018 has been posted in the Weekly Plan Section.

- The *Options Part 3* slide presentation has been posted.

##### 9/10/2018

- Added a Tutorials section which will contain lessons in the form of R scripts or R markdown files.  These are designed to be read and that you can worked through on your own.  We will also work through many of these in class together.

- New slide presentation called *Options Part 2* posted.


##### 9/5/2018

- I've added a couple of sections to the website - Slides and Q&A.  Check them out because they are amazing.

- Self-Study section also added - also amazing.

##### 9/4/2018

- **Homework for 9/11/2018** - there is nothing to turn in. Do the tasks listed in the Weekly Plan.  They consist of reading and working through tutorials.  I expect you to do the tasks, there is just nothing to turn in.  If you find a good introduction to options on the web, it will be helpful if you share in class on 