---
title: "Weekly Plan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This will serve as a rough guide for the course schedule.  I reserve right to change things as required.

&nbsp;


**Week 1 (9/4) Preliminaries**

We'll do the usual first class housekeeping including walking though the syllabus.  We'll also make sure that everyone has R & R Studio installed.  After that, we'll start discussing material material: files, directories, paths, touch-typing, keyboard shortcuts, vectors, dataframes, reading in data from a CSV, dataframe slicing.  We'll end the class by introducing options contracts.

*Assignment:* (Note: nothing to turn in)

- Read Chapter 5 ("Data Transformation"") of *R For Data Science* - **you should type out all the examples along with him**.

- Open a GitHub account.

- Complete the Software Carpentry Lesson on Git and GitHub:
http://swcarpentry.github.io/git-novice/

- Google around and find a short introduction to options.  Read it.  We will amass a list of the good ones in class and I will post them in the Self-Study section of the course website.

&nbsp;

**Week 2 (9/11) - Data Manipulation (1 of 2)** 

This week will be focused on gaining proficiency the data manipulation functions of the tidyverse `dplyr` package.  Towards this end we will perform an analysis on volume data published by the OCC.  The `dplyr` functions that we cover are: `filter()`, `arrange()`, `select()`, `mutate()`, `groupby()`, `summarize()`.  We learn how to create elegant sequences of dplyr functions using the pipe operator.  To end the class we will continue our discussion of options.

<!-- A brief history of R and why it’s used in data science.  Introduction to R: data types and syntax.  Various ways to run R code: interactive command line, scripts, notebooks.   Reading in data from external data sources. Basics of options. -->

<!-- IDEA: a simple visualization of the difference between calendar days and business days. I won't have them graph made up data, but this will be a nice opportunity for them to tell a little story with data and a visualization. -->

*Assignment:* (Note: nothing to turn in)

- Read chapters 19 ("Functions"), 20 ("Vectors""), and 21 ("Iteration") of *R For Data Science* - **Type out all the examples and also work through the exercise.  If you get stuck on any of the problems, just move on after a reasonable amount of effort**.

- Read the *Options Pricing* series of articles on Investopedia - https://www.investopedia.com/university/options-pricing/.  Or find something on your own and share with the class.

- Read Sections 1 - 3.4 of the the wikipedia article on Greeks: https://en.wikipedia.org/wiki/Greeks_(finance) . Don't read past section 3.4 (Theta).  None of the other greeks matter.

- Complete the exercises for the *Options Intro* data set in the Data section of the website.


&nbsp;


**Week 3 (9/18) - Data Manipulation (2 of 2)** 

This week we started by going over the Options Part 3 Slides, the discussion took longer that I anticipated but there was a lot of interest from the students in digging deeper into the finance material.  We ended the class by going over the dplyr tutorial again from start to finish, but only focusing on the essentials.  

*Assignment:* 

- Read and work through Chapter 3 ("Data Visualization"") and Chapter 18 ("Pipes"") of *R for Data Science*.  Note: the chapter numbers I give are from the online version of the book, they may be different for print versions. 


- Work through Part 1 ("A Quick Refresher"") of the DataCamp tutorial on writing functions in R - https://www.datacamp.com/courses/writing-functions-in-r.   The first section of the tutorial is free, but you have to pay to get access to the rest of the material.  Paying for the rest of the material is not required, but this will be a good introduction to a reputatable online data science education platform.


- Read and work through the "Data Structures", "Subsetting", and "Functions" chapters of *Advanced R* (all three can be can be found under the **Foundations** section).  As the title suggests, this book is more advanced so if you feel overwhelmed don't worry.  If you feel totally lost, you can simply focus on other material.  But as I always say, if you can type along with the examples and generate the same results with some understanding of what is going on, you are making progress. 


- Complete the exercises for the *OCC Volume Report* data set.


&nbsp;



**Week 4 (9/25) - R Markdown**   

First I'd like to get a sense of how the reading assignments and programming exercises are going for the students.  Then we'll introduce the concept of R Markdown, which is the backbone of R's extensive authoring capabilities. To end the class we'll explore the *Options History Practice* within an `.Rmd` notebook.  

*Assignment:* 

- Read and workthrough the **Communicate** section of R4DS.  In the online verison of the book this is Chapters 26-30, they are about various aspects of R Markdown.

- Complete all exercises for **Option History Practice** data set.

&nbsp;


**Week 5 (10/2) - Functions and Iteration**   

You now have a bit of experience performing data analysis in the form of single scripts written in `.R` file.  This week we will continue our use of R Markdown (`.Rmd`) files as we further explore the Practice Option Data.  Along the way we will discuss iteration and functions and iteration.


*Assignment:* 

- Form with three to five of your fellow students.  Create a team name, and nominate a team lead.  Most of my administrative communication will be with your team lead.  Have the team lead email me the name of your group, as well as any type of options-related analyis you might want to work on.  I don't know if I'll be able to accomodate requests, but some direction might be helpful.

- Catch-up on reading from previous assignments or working on previous exercises.

- Advanced Optional Reading: [A Layered Grammar of Graphics](pdf_wickham_layered_grammar.pdf) - by Hadley Wickham.  This article describes the foundations of Wickham's approach to creating `ggplot2`. 

&nbsp;

**Week 6 (10/9) - Data Visualization** 

Data Visualization with ggplot2().  An introduction to some of the most popular finance related packages on CRAN.  Discuss how to explore packages on your own and other self-study resources.

*Assignment:* 

- Reserve a meeting spot with me next week. 

- Read and work through these two tutorials on visualization by Bradley Boehmke.  There is a lot of material here so don't expect to complete it in a single week.  To really absorbe the material, try applying these techniques to the *Option History Practice Data*:
  - http://uc-r.github.io/quickplots
  - http://uc-r.github.io/gda

- I will also assign each team a preliminary exercise with the *Option History Practice* data that will relate to your project.  Your team lead has to e-mail me in order to get the assignment.

&nbsp;

**Week 7 (10/16) - NO CLASS - Meeting with Groups Individually**

There will not be regular class on this day.  Rather, I am going to meet with groups individually to discuss the projects.  The purpose of this meeting is for me to clearly articulate the project to you, and for me to assess where the students are in their understanding of the skills needed to complete the projects.  


To reserve as spot, talk to me after class on Tuesday 10/9, or e-mail me.

*Assignment:* 

- Continue working the Boehmke's visualization tutorials.

- Working on initial assignment for projects.

&nbsp;


**Week 8 (10/23) - Delta Neutral Daily File**

We apply our `dplyr` and `ggplot2` skills to analyze one of the Delta-Neutral EOD option pricing files.  It is these files, over many months and years, which form the foundation of our backtest data.

*Assignment*

- Work on initial assignment for projects.


&nbsp;


**Week 9 (10/30) - Delta-Hedging and Option Replication**

This week we focus on discussing the remaining options and derivatives material we will need for the course.

*Assignment*

- Work on initial assignment for projects.



&nbsp;


**Week 10 (11/6) - Joining Data**

It is often the case that you will have to combine together the data from multiple data sources. We discuss two of the `dplyr` functions that help you do this, namely `left_join()` and `inner_join()`.  

*Assignment:*

- Read and work through chapter 13 (Relational Data) or *R4DS*.

- I will send you the final project data with instructions, so start taking a look at that.


&nbsp;

  
**Week 11 (11/13) - Demonstration Analysis**

I will demonstrate the type of analysis that can be performed with the data.  This is meant to give you an idea of how to proceed with your own analysis.  We will also discuss the `bizdays` and `fOptions` packages.


&nbsp;

**Week 12 (11/20) - TBD**

&nbsp;

**Week 13 (11/27) - TBD**

&nbsp;

**Week 14 (12/4) - Install Python**

&nbsp;

**Week 15 (12/11) - Getting Started with Python**

